[package]
name = "favilla-examples"
version = "0.1.0"
edition = "2018"

[dependencies]
favilla = { path = "../favilla" }
ash = { version = "0.38", features = ["linked"] }
ash-window = "0.13"
raw-window-handle = "0.6.0"
vk-shader-macros = "0.2.8"
cgmath = "0.18"
thiserror = "1.0"
anyhow = "1.0"
memoffset = "0.6"
cstr = "0.2.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
sdl2 = { version = "0.37", features = ["raw-window-handle"] }
